# Generated by Django 4.2.3 on 2023-12-28 14:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0003_remove_job_selected_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hiring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('total_members', models.IntegerField()),
                ('event_location', models.CharField(max_length=200)),
                ('building_name', models.CharField(max_length=200)),
                ('selected_user', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), size=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
