# Generated by Django 4.2.3 on 2023-12-28 14:49

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0004_hiring'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='selected_user',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40, null=True), size=100),
        ),
    ]
