# Generated by Django 4.2.3 on 2024-01-04 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0009_alter_hiring_selected_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hiring',
            name='total_members',
            field=models.PositiveIntegerField(),
        ),
    ]
