# Generated by Django 4.2.3 on 2024-01-04 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0010_alter_hiring_total_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='vacancy',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
