# Generated by Django 4.2.3 on 2024-01-14 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0014_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='completed',
        ),
    ]
