# Generated by Django 4.2.3 on 2024-01-15 06:22

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0015_delete_completed'),
    ]

    operations = [
        migrations.CreateModel(
            name='completed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager_name', models.CharField(max_length=200)),
                ('event_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_location', models.CharField(max_length=200)),
                ('attend_user', django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=40), default=list, size=100)),
            ],
        ),
    ]
