# Generated by Django 4.2.3 on 2024-01-15 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0016_completed'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='completed',
            new_name='completed_jobs',
        ),
    ]
