# Generated by Django 4.2.3 on 2024-01-15 07:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0017_rename_completed_completed_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True, validators=[django.core.validators.RegexValidator('^\\d{10,15}$', message='Enter a valid phone number.')]),
        ),
    ]
