# Generated by Django 4.2.3 on 2024-01-16 03:57

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0018_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_jobs',
            name='attend_user',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=200), default=list, size=100),
        ),
    ]
