# Generated by Django 4.2.3 on 2024-01-16 04:00

from django.db import migrations, models
import django_jsonform.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0019_alter_completed_jobs_attend_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_jobs',
            name='attend_user',
            field=django_jsonform.models.fields.ArrayField(base_field=models.CharField(blank=True, max_length=170), default=list, size=100),
        ),
    ]
