# Generated by Django 4.2.3 on 2024-01-16 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0020_alter_completed_jobs_attend_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='hiring',
            name='event_day',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
