# Generated by Django 4.2.3 on 2024-01-16 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0021_hiring_event_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hiring',
            name='event_day',
        ),
    ]
