# Generated by Django 4.2.3 on 2024-01-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0022_remove_hiring_event_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.CharField(default='Enter your name', max_length=150),
        ),
    ]
