# Generated by Django 4.2.3 on 2024-01-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0023_customuser_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='ploc1',
            field=models.CharField(default='none', max_length=150),
        ),
        migrations.AddField(
            model_name='customuser',
            name='ploc2',
            field=models.CharField(default='none', max_length=150),
        ),
    ]
