# Generated by Django 4.2.3 on 2024-01-21 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalapp', '0025_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('1', 'jober'), ('2', 'hirer')], default='jober', max_length=15),
        ),
    ]
